zabbix_export:
  version: '7.4'
  template_groups:
    - uuid: 08afccc1647440e2bdf5025bd5f4b3e0
      name: BA/SSH
  templates:
    - uuid: ccb9478d71394cbf9ca818e33e887c22
      template: 'BA - SSH - MikroTik Config'
      name: 'BA - SSH - MikroTik Config'
      vendor:
        name: 'below average'
        version: 0.0.0.0
      groups:
        - name: BA/SSH
      items:
        - uuid: 017e9deb230d40bd81450232f827b526
          name: 'RouterOS Config'
          type: SSH
          key: 'ssh.run[export]'
          delay: 1d
          history: 90d
          value_type: TEXT
          params: 'export show-sensitive'
          username: '{$ROS_SSH_USER}'
          password: '{$ROS_SSH_PASS}'
          inventory_link: SOFTWARE_FULL
          tags:
            - tag: Config
      tags:
        - tag: Type
          value: SSH

